0
compound_cilk_spawn.c:1:1 keyword int
compound_cilk_spawn.c:1:5 identifier spawn_func
compound_cilk_spawn.c:1:16 punctuator (
compound_cilk_spawn.c:1:17 keyword int
compound_cilk_spawn.c:1:21 identifier arg
compound_cilk_spawn.c:1:24 punctuator )
compound_cilk_spawn.c:2:1 punctuator {
compound_cilk_spawn.c:3:3 keyword return
compound_cilk_spawn.c:3:10 identifier arg
compound_cilk_spawn.c:3:14 punctuator +
compound_cilk_spawn.c:3:16 constant 1
compound_cilk_spawn.c:3:17 punctuator ;
compound_cilk_spawn.c:4:1 punctuator }
compound_cilk_spawn.c:6:1 keyword int
compound_cilk_spawn.c:6:5 identifier check
compound_cilk_spawn.c:6:10 punctuator (
compound_cilk_spawn.c:6:11 punctuator )
compound_cilk_spawn.c:7:1 punctuator {
compound_cilk_spawn.c:8:3 keyword int
compound_cilk_spawn.c:8:7 identifier z
compound_cilk_spawn.c:8:8 punctuator ;
compound_cilk_spawn.c:9:3 identifier z
compound_cilk_spawn.c:9:5 punctuator =
compound_cilk_spawn.c:9:7 constant 23
compound_cilk_spawn.c:9:9 punctuator ,
compound_cilk_spawn.c:9:11 identifier _Cilk_spawn
compound_cilk_spawn.c:9:23 identifier spawn_func
compound_cilk_spawn.c:9:34 punctuator (
compound_cilk_spawn.c:9:35 constant 3
compound_cilk_spawn.c:9:36 punctuator )
compound_cilk_spawn.c:9:37 punctuator ,
compound_cilk_spawn.c:9:39 constant 3424
compound_cilk_spawn.c:9:43 punctuator ;
compound_cilk_spawn.c:10:3 constant 23
compound_cilk_spawn.c:10:5 punctuator ,
compound_cilk_spawn.c:10:7 identifier spawn_func
compound_cilk_spawn.c:10:18 punctuator (
compound_cilk_spawn.c:10:19 constant 5
compound_cilk_spawn.c:10:20 punctuator )
compound_cilk_spawn.c:10:21 punctuator ,
compound_cilk_spawn.c:10:23 identifier _Cilk_spawn
compound_cilk_spawn.c:10:35 identifier spawn_func
compound_cilk_spawn.c:10:46 punctuator (
compound_cilk_spawn.c:10:47 constant 3
compound_cilk_spawn.c:10:48 punctuator )
compound_cilk_spawn.c:10:49 punctuator ;
compound_cilk_spawn.c:11:3 identifier _Cilk_spawn
compound_cilk_spawn.c:11:15 identifier spawn_func
compound_cilk_spawn.c:11:26 punctuator (
compound_cilk_spawn.c:11:27 constant 0
compound_cilk_spawn.c:11:28 punctuator )
compound_cilk_spawn.c:11:29 punctuator ,
compound_cilk_spawn.c:11:31 identifier _Cilk_spawn
compound_cilk_spawn.c:11:43 identifier spawn_func
compound_cilk_spawn.c:11:54 punctuator (
compound_cilk_spawn.c:11:55 constant 3
compound_cilk_spawn.c:11:56 punctuator )
compound_cilk_spawn.c:11:57 punctuator ,
compound_cilk_spawn.c:11:59 constant 3
compound_cilk_spawn.c:11:60 punctuator ,
compound_cilk_spawn.c:11:62 identifier spawn_func
compound_cilk_spawn.c:11:73 punctuator (
compound_cilk_spawn.c:11:74 constant 0
compound_cilk_spawn.c:11:75 punctuator )
compound_cilk_spawn.c:11:76 punctuator ;
compound_cilk_spawn.c:12:3 keyword return
compound_cilk_spawn.c:12:10 constant 23
compound_cilk_spawn.c:12:12 punctuator ;
compound_cilk_spawn.c:13:1 punctuator }
