0
vector-shift.c:6:1 keyword int
vector-shift.c:6:5 identifier main
vector-shift.c:6:10 punctuator (
vector-shift.c:6:11 keyword int
vector-shift.c:6:15 identifier argc
vector-shift.c:6:19 punctuator ,
vector-shift.c:6:21 keyword char
vector-shift.c:6:26 punctuator *
vector-shift.c:6:27 identifier argv
vector-shift.c:6:31 punctuator [
vector-shift.c:6:32 punctuator ]
vector-shift.c:6:33 punctuator )
vector-shift.c:6:35 punctuator {
vector-shift.c:7:5 identifier __attribute__
vector-shift.c:7:18 punctuator (
vector-shift.c:7:19 punctuator (
vector-shift.c:7:20 identifier vector_size
vector-shift.c:7:31 punctuator (
vector-shift.c:7:32 punctuator (
vector-shift.c:7:33 constant 4
vector-shift.c:7:34 punctuator )
vector-shift.c:7:35 punctuator *
vector-shift.c:7:36 keyword sizeof
vector-shift.c:7:42 punctuator (
vector-shift.c:7:43 keyword char
vector-shift.c:7:47 punctuator )
vector-shift.c:7:48 punctuator )
vector-shift.c:7:49 punctuator )
vector-shift.c:7:50 punctuator )
vector-shift.c:7:52 keyword char
vector-shift.c:7:57 identifier vchar
vector-shift.c:7:63 punctuator =
vector-shift.c:7:65 punctuator {
vector-shift.c:7:66 constant 1
vector-shift.c:7:67 punctuator ,
vector-shift.c:7:68 constant 2
vector-shift.c:7:69 punctuator ,
vector-shift.c:7:70 constant 3
vector-shift.c:7:71 punctuator ,
vector-shift.c:7:72 constant 4
vector-shift.c:7:73 punctuator }
vector-shift.c:7:74 punctuator ;
vector-shift.c:8:5 identifier __attribute__
vector-shift.c:8:18 punctuator (
vector-shift.c:8:19 punctuator (
vector-shift.c:8:20 identifier vector_size
vector-shift.c:8:31 punctuator (
vector-shift.c:8:32 punctuator (
vector-shift.c:8:33 constant 4
vector-shift.c:8:34 punctuator )
vector-shift.c:8:35 punctuator *
vector-shift.c:8:36 keyword sizeof
vector-shift.c:8:42 punctuator (
vector-shift.c:8:43 keyword int
vector-shift.c:8:46 punctuator )
vector-shift.c:8:47 punctuator )
vector-shift.c:8:48 punctuator )
vector-shift.c:8:49 punctuator )
vector-shift.c:8:51 keyword int
vector-shift.c:8:55 identifier vint
vector-shift.c:8:60 punctuator =
vector-shift.c:8:62 punctuator {
vector-shift.c:8:63 constant 1
vector-shift.c:8:64 punctuator ,
vector-shift.c:8:65 constant 1
vector-shift.c:8:66 punctuator ,
vector-shift.c:8:67 constant 1
vector-shift.c:8:68 punctuator ,
vector-shift.c:8:69 constant 1
vector-shift.c:8:70 punctuator }
vector-shift.c:8:71 punctuator ;
vector-shift.c:10:5 identifier vint
vector-shift.c:10:10 punctuator <<=
vector-shift.c:10:14 identifier vchar
vector-shift.c:10:19 punctuator ;
vector-shift.c:11:5 identifier vchar
vector-shift.c:11:11 punctuator >>=
vector-shift.c:11:15 identifier vint
vector-shift.c:11:19 punctuator ;
vector-shift.c:13:5 keyword return
vector-shift.c:13:12 constant 0
vector-shift.c:13:13 punctuator ;
vector-shift.c:14:1 punctuator }
