0
struct-non-lval-1.c:2:1 keyword struct
struct-non-lval-1.c:2:8 identifier foo
struct-non-lval-1.c:2:12 punctuator {
struct-non-lval-1.c:2:13 keyword char
struct-non-lval-1.c:2:18 identifier x
struct-non-lval-1.c:2:19 punctuator ,
struct-non-lval-1.c:2:21 identifier y
struct-non-lval-1.c:2:22 punctuator ,
struct-non-lval-1.c:2:24 identifier z
struct-non-lval-1.c:2:25 punctuator [
struct-non-lval-1.c:2:26 constant 2
struct-non-lval-1.c:2:27 punctuator ]
struct-non-lval-1.c:2:28 punctuator ;
struct-non-lval-1.c:2:29 punctuator }
struct-non-lval-1.c:2:30 punctuator ;
struct-non-lval-1.c:3:1 keyword struct
struct-non-lval-1.c:3:8 identifier foo
struct-non-lval-1.c:3:12 identifier f
struct-non-lval-1.c:3:13 punctuator (
struct-non-lval-1.c:3:14 punctuator )
struct-non-lval-1.c:3:15 punctuator ;
struct-non-lval-1.c:4:1 keyword void
struct-non-lval-1.c:4:6 identifier bar
struct-non-lval-1.c:4:9 punctuator (
struct-non-lval-1.c:4:10 keyword int
struct-non-lval-1.c:4:14 identifier baz
struct-non-lval-1.c:4:17 punctuator )
struct-non-lval-1.c:5:1 punctuator {
struct-non-lval-1.c:6:3 identifier f
struct-non-lval-1.c:6:4 punctuator (
struct-non-lval-1.c:6:5 punctuator )
struct-non-lval-1.c:6:6 punctuator .
struct-non-lval-1.c:6:7 identifier z
struct-non-lval-1.c:6:8 punctuator [
struct-non-lval-1.c:6:9 identifier baz
struct-non-lval-1.c:6:12 punctuator ]
struct-non-lval-1.c:6:14 punctuator =
struct-non-lval-1.c:6:16 constant 1
struct-non-lval-1.c:6:17 punctuator ;
struct-non-lval-1.c:7:1 punctuator }
